### ISSUE TITLE
Switching stations resets the volume to 100% 

### ISSUE THREAD

**Issue by Annunaki** [AlbrechtL/welle.io#664] opened 2021-07-10 17:05 UTC
Output volume is reset to 100% when tuning to different stations, however, the Volume Slider remains at where it was set.

**Comment by AlbrechtL** [comment] 2021-12-28 22:38
Thanks for reporting!

**Comment by AlbrechtL** [comment] 2022-08-21 11:34
Is this bug is till occurring?

**Comment by SergeantSerk** [comment] 2022-08-22 11:40
Interestingly, I stumbled on this issue right now and was about to start an issue. Yes it is still occurring.

Switching stations resets the volume to 100% but the slider remains in the same position.

**Comment by AlbrechtL** [comment] 2022-12-16 22:26
Thanks for testing! Bug fix pull request are welcome!

**Comment by mdmitry** [comment] 2024-03-16 15:30
Still not fixed in 2024

**Comment by AlbrechtL** [comment] 2024-10-08 21:02
The described issue I can't reproduce. But I found another issue that the volume was always 100% after mute that is fixed here https://github.com/AlbrechtL/welle.io/commit/86a6fdad9b9eb44b47bf74564cacdec6a5d8ccd4.

Can you try it with this version (https://welle-io-nightlies.albrechtloh.de/20241008_86a6fdad_Windows_welle-io-setup_x64.exe), please?

**Closed** 2024-10-08 21:03 UTC
Labels: bug
