### ISSUE TITLE
Radiocontroller: Restart syncing. isSync: true. isFICCRC false. FrameErrors 25

### ISSUE THREAD

**Issue by gtekprog** [AlbrechtL/welle.io#85] opened 2017-06-12 19:56 UTC
Hello Gents,

I receive this error ( with a complete ofdm resync ) after a fixed period. Always 25 frameErrors.

What is wrong?

BR

**Comment by AlbrechtL** [comment] 2017-06-13 06:26
Please tell us your location (country), channel (frequency) and station. Does it happen only with a specific station in one channel or with all stations?  

If possible record a [RAW file](https://www.welle.io/devices/rawfile#record-an-u8-raw-file) and provide it to use.

**Comment by gtekprog** [comment] 2017-06-13 07:18
Hi Albrecht,

IT is in the Netherlands . Channel 5D.
The station uses odr software ( IT is ours )

Br.

Evert

Albrecht Lohofener <notifications@github.com> schreef op 13 juni 2017 08:26:08 CEST:
>Please tell us your location (country), channel (frequency) and
>station. Does it happen only with a specific station in one channel or
>with all stations?  
>
>If possible record a [RAW
>file](https://www.welle.io/devices/rawfile#record-an-u8-raw-file) and
>provide it to use.
>
>-- 
>You are receiving this because you authored the thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/AlbrechtL/welle.io/issues/85#issuecomment-308019583

--

**Comment by AlbrechtL** [comment] 2017-06-13 11:32
Please provide us a [I/Q RAW file](https://www.welle.io/devices/rawfile#record-an-u8-raw-file). This file contains the modulated signal as it is broadcasted. With this file we can reproduce the bug.

**Comment by gtekprog** [comment] 2017-06-13 13:06
Hi Albrecht,
Will send you the RAW file tonight. It could as well be that our MUX is producing skips. However, this is not heard, seen on other DAB+ radio's.
Evert
----Origineel Bericht----
Van : notifications@github.com
Datum : 13/06/2017 13:32
Aan : welle.io@noreply.github.com
Cc : spambox2016@telfort.nl, author@noreply.github.com
Onderwerp : Re: [AlbrechtL/welle.io] Radiocontroller: Restart syncing. isSync: true. isFICCRC false. FrameErrors 25 (#85)
Please provide us a I/Q RAW file. This file contains the modulated signal as it is broadcasted. With this file we can reproduce the bug.

**Comment by andimik** [comment] 2017-06-14 14:02
Off topic: see http://wohnort.org/dab/ where Carey reports double IDs on different ensembles... Shall be fixed in order to guarantee better handling on user side.

**Comment by AlbrechtL** [comment] 2017-07-25 20:30
Closed because there are no more information to reproduce the problem.

**Closed by AlbrechtL** 2017-07-25 20:30 UTC
Labels: bug
