### ISSUE TITLE
[welle-cli] Crash on illegal UTF-8

### ISSUE THREAD

**Issue by gvanem** [AlbrechtL/welle.io#296] opened 2018-09-05 10:40 UTC
Running `welle-cli` on Windows crashes deep inside `WebRadioInterface::serve()` for no obvious reason. Tested with Google Chrome and `welle-cli.exe -C1 -w 1212 -c 12B`.

After adding a `try / catch` block around `fut.get()` inside `WebRadioInterface::serve()`, I can see the error is:
```
Exception: [json.exception.type_error.316] invalid UTF-8 byte at index 6: 0x72
```
Lots of these. But what are they and why? Could it be one of these:
  * `s.serviceLabel.utf8_label()`
  * `s.serviceLabel.utf8_shortlabel()`

since if I run `welle-cli.exe -c 12B -D`, there are these services with seemingly illegal UTF-8 encoding:
```
Service list
**** Enter '.' to quit.
New Service: 0xf304 'NRK Vµr Vest    '
...
New Service: 0xf205 'NRK S┴PMI       '
```

**Comment by mpbraendli** [comment] 2018-09-05 12:34
Mmmmh weird... It must be either Labels or DLS. What character encoding is this ensemble using?

Does it crash if you run the receiver without accessing the webpage? If yes, please run the receiver, and execute `wget http://localhost:1212/fic`, let it run for a minute, Ctrl-C it, and send me the file with the FIC.

**Comment by gvanem** [comment] 2018-09-05 12:53
> What character encoding is this ensemble using?

No idea really (ISO-8859-2 from the looks of the debug). How can figure out that?

> Does it crash if you run the receiver without accessing the webpage?

No.

**Comment by andimik** [comment] 2018-09-05 13:03
Can you try it with 12D, Riks? 

https://www.fmlist.org/sendertabelle/dab-ww_more.php?inputLand=NOR&inputEn=F201

They don't have Norwegian characters in the label.

**Comment by mpbraendli** [comment] 2018-09-05 13:09
> No idea really (ISO-8859-2 from the looks of the debug). How can figure out that?

It's easiest, both for you and for me, to make the FIC dump I mentioned earlier.

I wrote "if yes" in my previous message, but I actually meant "if no" (because it wouldn't make sense otherwise :-D)

Can you send me a one minute FIC dump?

**Comment by gvanem** [comment] 2018-09-05 13:17
Same thing, but at a different offset:
```
Exception: [json.exception.type_error.316] invalid UTF-8 byte at index 10: 0x3A
```
But with `welle-cli.exe -CN -w 1212 -c 12D`, I do get sound and a Audio bar:
![welle-io-r-rock](https://user-images.githubusercontent.com/945271/45095592-b9d9e400-b11e-11e8-98c2-db6972f0cb0f.png)

The DLS text looks fine. But the json exception is maybe related to some problem in `charsets.cpp`?

**Comment by mpbraendli** [comment] 2018-09-05 13:28
Yes thanks. That file somehow makes etisnoop segfault, but I can probably analyse something already.

**Comment by mpbraendli** [comment] 2018-09-05 13:39
I am confident it's using Charset 0, i.e. EBU-Latin.

**Comment by mpbraendli** [comment] 2018-09-05 13:56
I ran a test with a custom ensemble with labels containing accents, it seems to work with welle-cli: 
![image](https://user-images.githubusercontent.com/5902825/45097710-bf85f880-b123-11e8-9196-8859b3ed8da3.png)

It's also using charset 0.

Maybe there is one character in a label that is not correctly decoded? I can check this using your FIC dump.

**Comment by gvanem** [comment] 2018-09-05 14:59
> It's also using charset 0.

IOW `CharacterSet::EbuLatin`. I've being trying to understand what the `toUtf8StringUsingCharset()` function does. The default parameter `num_bytes = 0` and the comment says:
```
 * If num_bytes is nonzero, the buffer must be zero
 * terminated.
```
Then why is this:
```c
                if (num_bytes == 0) {
                    while (*buf) {
                        s += ebuLatinToUcs2[*buf];
                        buf++;
                    }
                }
```
assuming `buf` is 0-terminated? That's the opposite of what the comment says. Is the comment wrong?

**Comment by gvanem** [comment] 2018-09-13 11:54
> the browser window does not show anything.

`welle-cli` needs `index.html` and `index.js` in it's directory. Are they? I do not use the `make install`, so I can't tell if it does the copy.

**Comment by mpbraendli** [comment] 2018-09-13 12:03
Correct. There ought to be a cross platform way to

1. copy `index.html` and `index.js` to the right place on `make install`;
1. tell the `welle-cli` binary where this right place is.

I don't know how to do that.

PS:
you should have opened a new issue, as this is a completely different topic.

**Comment by andimik** [comment] 2018-09-13 15:14
Sure. But I thought I made a mistake ...

**Comment by AlbrechtL** [comment] 2018-09-13 17:10
Is the origin issue still exists? If yes, are they any RAW files to test?

BTW: In the latest Windows installer, welle-cli is included incl. the HTML and JS files. If it is not working as expected please open new issues.

**Comment by AlbrechtL** [comment] 2018-09-19 18:45
Can you reproduce the issue now?

**Comment by gvanem** [comment] 2018-09-24 08:17
> Can you reproduce the issue now?

The problem is still present. Welle-cli should be able to cope with illegal UTF-8 sequences.

**Comment by mpbraendli** [comment] 2018-09-24 08:26
Just to clarify my understanding of the issue, I don't see where these illegal UTF-8 sequences come from. Your ensemble contains EBU Latin encoded labels, and we convert these to UCS-2 using the function you also inspected.

I checked that the function generating UCS-2 generates valid output for all 255 possible input values (EBU Latin, skipping '\0').

It's not clear to me how to proceed. I would suggest you add `try` `catch` blocks in the `send_mux_json` function around those places where the labels are being inserted into the json. Then analyse the byte sequence when something fails.

Or maybe you'll find out that it's not the labels, which would help us further.

**Comment by andimik** [comment] 2018-09-24 08:44
Could you share an eti file?

**Comment by mpbraendli** [comment] 2018-09-24 09:44
Since this is an over-the-air signal, and IQ file would be better, as the regenerated ETI will probably contain errors (like the FIC dump).

**Comment by AlbrechtL** [comment] 2018-12-27 08:30
Any news here? Can we close it?

**Comment by AlbrechtL** [comment] 2019-03-03 10:17
I'm closing it because of inactivity.

**Closed by AlbrechtL** 2019-03-03 10:17 UTC

**Comment by andimik** [comment] 2020-11-28 19:06
As I'm now able to receive all NRK DAB+ ensembles via satellite, I've tested it (under Ubuntu). It does not crash, but I have the fic-file for you.

![grafik](https://user-images.githubusercontent.com/24510556/100523989-c5f56480-31b4-11eb-81f1-893787e90731.png)

[nrk2.zip](https://github.com/AlbrechtL/welle.io/files/5611102/nrk2.zip)
(contains `nrk2.fic` file)

**Comment by andimik** [comment] 2020-11-28 19:34
And here there is an eti file (which I was using to produce the u8 stream with **odr-dabmod** and to feed into **welle-cli**)

https://www.file-upload.net/download-14380952/nrk2.eti.zip.html

**Comment by gvanem** [comment] 2020-11-29 07:38
@andimik Chrome says "nrk2.eti.zip can be dangerous. So Chrome has blocked it". 
Besides I've forgot about this issue **and** it's impossible to build `welle-cli.exe` for me now due to C++ errors.
Besides how shall I use these .fic files?

**Comment by andimik** [comment] 2020-11-29 08:17
Then use another browser...

You should only download these two files if you know what to do with them.

**Comment by andimik** [comment] 2020-11-29 10:02
I've tried under Windows 10 now and have no problems with words like Østlands, Vær Sør, SÁPMI or Mjøsbyene.

![grafik](https://user-images.githubusercontent.com/24510556/100538632-2f1abd80-3231-11eb-8f21-ec498e760625.png)

![grafik](https://user-images.githubusercontent.com/24510556/100538779-07782500-3232-11eb-82e1-a8b8904f3311.png)


Have you tried to use the setup.exe file from https://bintray.com/albrechtl/welle.io/welle.io_nightly#files ? In the installation folder you will find `c:\Program Files (x86)\welle.io\welle-cli.exe`

**Comment by AlbrechtL** [comment] 2021-03-06 19:39
@andimik Thanks for testing!
