### ISSUE TITLE
[Raspberry pi 3B+] Output device Null

### ISSUE THREAD

**Issue by Ale268** [AlbrechtL/welle.io#721] opened 2022-03-07 12:31 UTC
Hello there

Thak you for the great software, used it under windows and wanted it to now also run on a rpi3b+.

After finaly being able to build it using cmake it looked promising but it always fails using the output device "null".

It is running beside Moode Audio. Alsa is the used audio driver there. 
![20220307_130222](https://user-images.githubusercontent.com/46281437/157034801-efb4e932-0989-4579-be64-fab8823cb475.jpg)

Attached a picture of the console out.

Let me know what other logs or informations you need!

Thank you beforehand and greetings from switzerland.

**Comment by Seppklaus** [comment] 2022-03-16 21:25
I have/had the same issue. Excellent reception with my Linux-Laptop and MacBook. No reception with the RPI3b+. I used the same rtl-sdr and the same antenna setup.
I then tried it with a RPI4 and same SD-Card and it works. I use the USB3 port on the RPI4.

I believe the problem is the power and quality of the RPI3 USB ports. Maybe it works with an additional power supply for the rtl-sdr but I don't have the cable to try it with my RPI3.

Maybe some one else can confirm that the issues with the RPI3 are due to the power of the USB port - or not.

**Comment by AlbrechtL** [comment] 2022-08-21 11:55
Thanks for reporting. The issue is that welle.io doesn't find an audio output interface. Did you use the latest Raspberry OS?

**Comment by Ale268** [comment] 2022-08-22 20:24
Hello there

Thank you for Answering. 
I am trying to get it running on a RPI3B+ which is running moodeaudio as its base operating System. 
Moode is just an adapted Raspbian though. 

![grafik](https://user-images.githubusercontent.com/46281437/186011976-d858154c-a4ff-4874-a176-0c504bbf1a77.png)
Here are all the related versions.

The audio output device is an I2S Board (Hifiberry DAC+ DSP).

**Comment by Ale268** [comment] 2022-08-22 20:31
> 



> However, I installed it simply with:
> sudo apt install welle.io

When I try to do so it won't find anything
![grafik](https://user-images.githubusercontent.com/46281437/186013193-0488d7d6-9738-470b-83fb-be4bb7636ab0.png)

**Comment by AlbrechtL** [comment] 2022-12-16 22:18
In the latest Raspberry OS welle.io is included.

**Comment by AlbrechtL** [comment] 2022-12-16 22:18
For now I'm closing this issue.

**Closed by AlbrechtL** 2022-12-16 22:18 UTC
Labels: question

**Comment by Ale268** [comment] 2023-06-28 19:41
I have now installed everything again but the output device is still null.
