### ISSUE TITLE
EPG data

### ISSUE THREAD

**Issue by ubuntu-novize** [AlbrechtL/welle.io#568] opened 2020-06-25 07:53 UTC
Hi, some DAB+ radio stations (Hessischer Rundfunk...) transmit EPG data (like TV).
Will welle.io support in future versions the display of this data?

**Comment by mpbraendli** [comment] 2020-06-25 08:12
Hello, I think this is a duplicate of #558.

**Closed by mpbraendli** 2020-06-25 08:12 UTC
