### ISSUE TITLE
 [Manjaro Linux (x64)] sound problem

### ISSUE THREAD

**Issue by zygmund2000** [AlbrechtL/welle.io#17] opened 2017-03-16 10:15 UTC
Sound problem under linux Manjaro x64, after some time sound is very dropped.

**Comment by AlbrechtL** [comment] 2017-03-16 20:38
Can you explain the problem a little more in detail, please.
How is your signal quality? Are all three fields in the right top corner green? If no than you have a bad DAB reception.

**Comment by zygmund2000** [comment] 2017-03-16 20:57
My singnal is 20dB SNR and very good spectrum, afer start audio is ok but atere some time about 1-2min is not posiible to listen, for example qt-dab works without problems.

**Comment by AlbrechtL** [comment] 2017-03-16 21:09
Can you post the output from the command line?

qt-dab uses portaudio for the audio output while welle.io uses QT multimedia for the audio output. Obviously this makes a difference.

**Comment by zygmund2000** [comment] 2017-03-16 21:29
Audio: IdleState
Audio: StoppedState
Audio: ActiveState
Audio: ActiveState
Audio: IdleState
Audio: StoppedState
Audio: ActiveState
Audio: ActiveState
Audio: IdleState
Audio: StoppedState
Audio: ActiveState
Audio: ActiveState
Audio: IdleState
Audio: StoppedState
Audio: ActiveState
Audio: ActiveState
Audio: IdleState
Audio: StoppedState
Audio: ActiveState
Audio: ActiveState
Audio: IdleState
Audio: StoppedState
Audio: ActiveState
Audio: ActiveState
Audio: IdleState
Audio: StoppedState

**Comment by AlbrechtL** [comment] 2017-03-16 21:38
Which QT version do you use?

**Comment by zygmund2000** [comment] 2017-03-17 08:00
I installed from this link: https://www.qt.io/download-open-source/ and default checked 5.8

**Comment by zygmund2000** [comment] 2017-03-17 09:09
I'm using pulseaudio with default sample rate 48khz, this problem looks like audio data speed mismatch, eg sound card plays faster or slower then decoded from your app.

**Comment by AlbrechtL** [comment] 2017-03-17 14:07
How it sounds like? If you cards plays it faster or slower you should hear it.

**Comment by zygmund2000** [comment] 2017-03-17 14:52
LOL if difference is like 48000 or 48002 will you hear it?

**Comment by AlbrechtL** [comment] 2017-03-19 13:18
Can you compile the latest version and test it again, please?
I added some audio [code](e3c2e68) thats avoids that the sound cards stops playing.

BTW: Do you have a special sound card?

**Comment by zygmund2000** [comment] 2017-03-20 09:18
Still same problem, I don't have special sound card, just internal in laptop, I have other machine with different sound card but audio is also not continuous.

**Comment by AlbrechtL** [comment] 2017-03-24 19:18
Did you activate the expert view? Does it also happen with deactivated expert view?

**Comment by AlbrechtL** [comment] 2017-03-26 07:42
May it is the problem https://github.com/AlbrechtL/welle.io/issues/35. Please report if it is this issue!

**Comment by AlbrechtL** [comment] 2017-03-28 08:43
@zygmund2000: Thanks for reporting. I close this issue because the problem is explained in issue #35.

**Closed by AlbrechtL** 2017-03-28 08:43 UTC
Labels: bug, duplicate
